// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The Hyperlight Authors.

//! Derives the snapshot key from what a snapshot depends on, so that only
//! a change to those refuses a saved snapshot; see `SNAPSHOT_KEY` in the
//! library.  Also embeds the `hluk init` templates into the binary.

use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

/// The host side of the guest contract: the host functions and their
/// meaning, the I/O stack sizes, the heap and scratch layout, the guest
/// MSR list, and the hyperlight-host release that reads a snapshot.  Bump
/// it when any of those changes in a way a snapshot would notice; a
/// kernel change rolls the key by itself.
const SNAPSHOT_CONTRACT: u32 = 1;

/// The embedded kernel, whose code and host-call protocol a snapshot
/// carries in its memory.
const KERNEL: &str = "kernel/elfloader_hyperlight-x86_64";

/// The `hluk init` templates: one directory each, every file in it copied
/// into a new project.  Embedded so a project can be started offline (only
/// its rootfs is fetched) and so the templates match the binary's release.
const TEMPLATES: &str = "templates";

fn main() {
    println!("cargo:rerun-if-changed={KERNEL}");
    println!("cargo:rerun-if-changed=build.rs");
    let kernel = std::fs::read(KERNEL).expect("the embedded kernel is in the tree");
    let hash: String = Sha256::digest(&kernel)
        .iter()
        .take(8)
        .map(|b| format!("{b:02x}"))
        .collect();
    println!("cargo:rustc-env=HLUK_SNAPSHOT_KEY=k{hash}-c{SNAPSHOT_CONTRACT}");

    embed_templates();
}

/// Write `$OUT_DIR/templates.rs`: a `TEMPLATES` slice with one entry per
/// directory under `templates/`, each file's contents pulled in with
/// `include_str!`.  Paths inside a template use `/` whatever the host, so
/// the list reads the same on every platform; the CLI turns them into
/// native paths when it writes a project.
fn embed_templates() {
    // A directory here makes cargo rescan it, so a new or edited template
    // file rebuilds the binary.
    println!("cargo:rerun-if-changed={TEMPLATES}");
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = manifest_dir.join(TEMPLATES);
    let mut dirs: Vec<PathBuf> = fs::read_dir(&root)
        .expect("templates/ is in the tree")
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();

    let mut out = String::from(
        "// @generated by build.rs from templates/; do not edit.\n\
         pub static TEMPLATES: &[TemplateSource] = &[\n",
    );
    for dir in dirs {
        let name = dir.file_name().unwrap().to_string_lossy();
        let mut files = Vec::new();
        collect_files(&dir, &dir, &mut files);
        files.sort();
        out.push_str(&format!(
            "    TemplateSource {{\n        name: {name:?},\n        files: &[\n"
        ));
        for (rel, abs) in files {
            out.push_str(&format!("            ({rel:?}, include_str!({abs:?})),\n"));
        }
        out.push_str("        ],\n    },\n");
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("templates.rs");
    fs::write(dest, out).unwrap();
}

/// Every file under `dir`, as (path relative to `base` with `/` separators,
/// absolute path as a string for `include_str!`).
fn collect_files(base: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    for entry in fs::read_dir(dir).unwrap().filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            collect_files(base, &path, out);
        } else {
            let rel = path
                .strip_prefix(base)
                .unwrap()
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((rel, path.to_string_lossy().into_owned()));
        }
    }
}
